name: "Build check on PR"

on:
    pull_request:
        branches:
            - main

jobs: 
    build:
        name: "Build the project"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
            - name: "Install dependencies"
              run: npm install
            - name: "Run build"
              run: npm run build